name: CI/CD Pipeline

on:
  push:
    branches: [main, jenkins_WIP]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Build Docker image
        run: |
          docker build -t ci-cd-pipeline-project .

      - name: Test application
        run: |
          docker run --rm ci-cd-pipeline-project npm test
